/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package analisasistem.view.calendarbooking;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Raka New
 */
public class CalendarBookingPanel extends javax.swing.JPanel {

    /**
     * Creates new form CalendarBookingPanel
     */
    private analisasistem.controller.CalendarBookingPanelController controller;
    
    public CalendarBookingPanel() {
        initComponents();
        this.controller = new analisasistem.controller.CalendarBookingPanelController(this);
        this.defaultConfig();
    }
    private void defaultConfig(){
        this.controller.isiTable();
        this.controller.defaultConfig();
        this.styleTable();
        
    }
    
    private void styleTable(){
        analisasistem.library.TableStyle style = new analisasistem.library.TableStyle();
        int[] lebar;
        lebar = new int[this.controller.getJumlahHari()+2];
        lebar[0]  = 60;
        lebar[1]  = 150;
        for(int i=0;i<this.controller.getJumlahHari();i++){
            lebar[i+2] = 30;
        }
        style.setCalendarBooking(this.getTbPegawai(),lebar,true);
    }
    
    public void styleBookingCartTable(){
        analisasistem.library.TableStyle style = new analisasistem.library.TableStyle();
        style.setSize(this.getTbBookingCart(), new int[]{15,20,50,50}, true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbCalendarBooking = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jcbYears = new javax.swing.JComboBox();
        jcbMonth = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBookingCart = new javax.swing.JTable();
        btnForm = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnReg = new javax.swing.JButton();

        tbCalendarBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCalendarBooking.setCellSelectionEnabled(true);
        tbCalendarBooking.setGridColor(new java.awt.Color(204, 204, 204));
        tbCalendarBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCalendarBookingMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCalendarBooking);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Kampus\\SEMESTER VI\\ADSI\\Perangkat Lunak\\AnalisaSistem\\images\\blue\\female-user.png")); // NOI18N
        jLabel1.setText("Calendar Booking");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jcbYears.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbBookingCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tbBookingCart);

        btnForm.setText("Do RSV");
        btnForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnReg.setText("Do REG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbYears, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnForm)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnView});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnForm, btnReg});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnView)
                        .addComponent(btnAdd)
                        .addComponent(jcbYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnForm)
                            .addComponent(btnClear)
                            .addComponent(btnReg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbCalendarBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCalendarBookingMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            
        }

    }//GEN-LAST:event_tbCalendarBookingMouseClicked

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            // TODO add your handling code here:
            this.controller.addReservation();
        } catch (ParseException ex) {
            Logger.getLogger(CalendarBookingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormActionPerformed
        // TODO add your handling code here:
        this.controller.fillForm();
    }//GEN-LAST:event_btnFormActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnForm;
    private javax.swing.JButton btnReg;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcbMonth;
    private javax.swing.JComboBox jcbYears;
    private javax.swing.JTable tbBookingCart;
    private javax.swing.JTable tbCalendarBooking;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnView
     */
    public javax.swing.JButton getBtnView() {
        return btnView;
    }

    /**
     * @param btnView the btnView to set
     */
    public void setBtnView(javax.swing.JButton btnView) {
        this.btnView = btnView;
    }



    /**
     * @return the tbPegawai
     */
    public javax.swing.JTable getTbPegawai() {
        return getTbCalendarBooking();
    }

    /**
     * @param tbPegawai the tbPegawai to set
     */
    public void setTbPegawai(javax.swing.JTable tbPegawai) {
        this.setTbCalendarBooking(tbPegawai);
    }

    /**
     * @return the jcbMonth
     */
    public javax.swing.JComboBox getJcbMonth() {
        return jcbMonth;
    }

    /**
     * @param jcbMonth the jcbMonth to set
     */
    public void setJcbMonth(javax.swing.JComboBox jcbMonth) {
        this.jcbMonth = jcbMonth;
    }

    /**
     * @return the jcbYears
     */
    public javax.swing.JComboBox getJcbYears() {
        return jcbYears;
    }

    /**
     * @param jcbYears the jcbYears to set
     */
    public void setJcbYears(javax.swing.JComboBox jcbYears) {
        this.jcbYears = jcbYears;
    }

    /**
     * @return the btnAdd
     */
    public javax.swing.JButton getBtnAdd() {
        return btnAdd;
    }

    /**
     * @param btnAdd the btnAdd to set
     */
    public void setBtnAdd(javax.swing.JButton btnAdd) {
        this.btnAdd = btnAdd;
    }

    /**
     * @return the btnClear
     */
    public javax.swing.JButton getBtnClear() {
        return btnClear;
    }

    /**
     * @param btnClear the btnClear to set
     */
    public void setBtnClear(javax.swing.JButton btnClear) {
        this.btnClear = btnClear;
    }

    /**
     * @return the btnForm
     */
    public javax.swing.JButton getBtnForm() {
        return btnForm;
    }

    /**
     * @param btnForm the btnForm to set
     */
    public void setBtnForm(javax.swing.JButton btnForm) {
        this.btnForm = btnForm;
    }

    /**
     * @return the tbBookingCart
     */
    public javax.swing.JTable getTbBookingCart() {
        return tbBookingCart;
    }

    /**
     * @param tbBookingCart the tbBookingCart to set
     */
    public void setTbBookingCart(javax.swing.JTable tbBookingCart) {
        this.tbBookingCart = tbBookingCart;
    }

    /**
     * @return the tbCalendarBooking
     */
    public javax.swing.JTable getTbCalendarBooking() {
        return tbCalendarBooking;
    }

    /**
     * @param tbCalendarBooking the tbCalendarBooking to set
     */
    public void setTbCalendarBooking(javax.swing.JTable tbCalendarBooking) {
        this.tbCalendarBooking = tbCalendarBooking;
    }
}
