/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package analisasistem.view.laundry;

import analisasistem.controller.LaundryServicePanelController;
import analisasistem.entity.LaundryService;
import analisasistem.library.OtomatisasiId;

/**
 *
 * @author Raka New
 */
public class LaundryServicePanel extends javax.swing.JPanel {
    private LaundryServicePanelController controller;
    private boolean updateBool;
    /**
     * Creates new form LaundryServicePanel
     */
    public LaundryServicePanel() {
        initComponents();
        this.controller = new LaundryServicePanelController(this);
        this.controller.isiTable();
       
        this.defaultConfig();
    }
    private void defaultConfig(){
        analisasistem.library.TableStyle style = new analisasistem.library.TableStyle();
        style.setSize(this.getTbLaundryService(), new int[]{20,250,100},true);
        this.setUpdateBool(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLaundryService = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txKode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txBiaya = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txKeterangan = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Kampus\\SEMESTER VI\\ADSI\\Perangkat Lunak\\AnalisaSistem\\images\\blue\\cloud-filled.png")); // NOI18N
        jLabel1.setText("Data Laundry Service");

        tbLaundryService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbLaundryService.setGridColor(new java.awt.Color(204, 204, 204));
        tbLaundryService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLaundryServiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLaundryService);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Form Data Laundry Service"));

        jLabel2.setText("Kode");

        txKode.setEnabled(false);

        jLabel3.setText("Name");

        jLabel4.setText("Biaya");

        txKeterangan.setColumns(20);
        txKeterangan.setRows(5);
        jScrollPane2.setViewportView(txKeterangan);

        jLabel5.setText("Keterangan");

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnOK.setText("Save");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txKode)
                    .addComponent(txNama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txBiaya, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHapus, btnOK, jButton1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnHapus)
                    .addComponent(jButton1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        if(!this.isUpdateBool()){
            this.controller.insert();
            this.controller.isiTable();
            this.defaultConfig();
        }else if(this.isUpdateBool()){
            this.controller.update();
        }
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void tbLaundryServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLaundryServiceMouseClicked
        // TODO add your handling code here:
        this.controller.viewById();
    }//GEN-LAST:event_tbLaundryServiceMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        this.controller.delete();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.controller.reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnOK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbLaundryService;
    private javax.swing.JTextField txBiaya;
    private javax.swing.JTextArea txKeterangan;
    private javax.swing.JTextField txKode;
    private javax.swing.JTextField txNama;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnHapus
     */
    public javax.swing.JButton getBtnHapus() {
        return btnHapus;
    }

    /**
     * @param btnHapus the btnHapus to set
     */
    public void setBtnHapus(javax.swing.JButton btnHapus) {
        this.btnHapus = btnHapus;
    }

    /**
     * @return the btnOK
     */
    public javax.swing.JButton getBtnOK() {
        return btnOK;
    }

    /**
     * @param btnOK the btnOK to set
     */
    public void setBtnOK(javax.swing.JButton btnOK) {
        this.btnOK = btnOK;
    }

    /**
     * @return the txBiaya
     */
    public javax.swing.JTextField getTxBiaya() {
        return txBiaya;
    }

    /**
     * @param txBiaya the txBiaya to set
     */
    public void setTxBiaya(javax.swing.JTextField txBiaya) {
        this.txBiaya = txBiaya;
    }

    /**
     * @return the txKeterangan
     */
    public javax.swing.JTextArea getTxKeterangan() {
        return txKeterangan;
    }

    /**
     * @param txKeterangan the txKeterangan to set
     */
    public void setTxKeterangan(javax.swing.JTextArea txKeterangan) {
        this.txKeterangan = txKeterangan;
    }

    /**
     * @return the txKode
     */
    public javax.swing.JTextField getTxKode() {
        return txKode;
    }

    /**
     * @param txKode the txKode to set
     */
    public void setTxKode(javax.swing.JTextField txKode) {
        this.txKode = txKode;
    }

    /**
     * @return the txNama
     */
    public javax.swing.JTextField getTxNama() {
        return txNama;
    }

    /**
     * @param txNama the txNama to set
     */
    public void setTxNama(javax.swing.JTextField txNama) {
        this.txNama = txNama;
    }

    /**
     * @return the tbLaundryService
     */
    public javax.swing.JTable getTbLaundryService() {
        return tbLaundryService;
    }

    /**
     * @param tbLaundryService the tbLaundryService to set
     */
    public void setTbLaundryService(javax.swing.JTable tbLaundryService) {
        this.tbLaundryService = tbLaundryService;
    }

    /**
     * @return the updateBool
     */
    public boolean isUpdateBool() {
        return updateBool;
    }

    /**
     * @param updateBool the updateBool to set
     */
    public void setUpdateBool(boolean updateBool) {
        this.updateBool = updateBool;
    }
}
