/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package analisasistem.view.pegawai;

import analisasistem.view.pegawai.PegawaiPanel;
import analisasistem.controller.pegawai.PegawaiDialogController;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Raka New
 */
public class FormPegawaiDialog extends javax.swing.JDialog {

    /**
     * Creates new form FormPegawaiDialog
     */
    private int action =1; // 1 : simpan, 2 : update
    private Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize();
    private PegawaiDialogController controller;
    PegawaiPanel panelPegawai;
    public FormPegawaiDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(dimensi.width/2 - this.getWidth()/2, dimensi.height/2 - this.getHeight()/2);
        this.controller = new PegawaiDialogController(this);
    }
    
    public void viewDataPegawai(){
        this.controller.viewDataPegawai();
    }
    
    public void setId(){
        this.controller.setId();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        dateChooserLahir = new com.toedter.calendar.JDateChooser();
        txPhone = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txAreaAlamat = new javax.swing.JTextArea();
        txTempatLahir = new javax.swing.JTextField();
        txNama = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txProvinsi = new javax.swing.JTextField();
        radioLaki = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txKota = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        radioPerempuan = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jcbJabatan = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Pegawai");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnSimpan});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        dateChooserLahir.setDateFormatString("yyyy-MM-dd");
        dateChooserLahir.setMaxSelectableDate(new java.util.Date(253370797270000L));
        dateChooserLahir.setMinSelectableDate(new java.util.Date(-62135737130000L));

        txAreaAlamat.setColumns(20);
        txAreaAlamat.setRows(3);
        jScrollPane2.setViewportView(txAreaAlamat);

        jLabel13.setText("Tempat Lahir");

        txProvinsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txProvinsiActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioLaki);
        radioLaki.setText("Laki- laki");

        jLabel11.setText("Nama");

        jLabel14.setText("Tanggal Lahir");

        txId.setEnabled(false);

        jLabel12.setText("Jenis Kelamin");

        jLabel15.setText("Alamat");

        txKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txKotaActionPerformed(evt);
            }
        });

        jLabel17.setText("Kota");

        jLabel18.setText("Telphone");

        buttonGroup1.add(radioPerempuan);
        radioPerempuan.setText("Perempuan");

        jLabel10.setText("ID");

        jLabel16.setText("Provinsi");

        jcbJabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Jabatan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txId)
                    .addComponent(txNama)
                    .addComponent(txTempatLahir)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(txPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(txKota)
                    .addComponent(txProvinsi)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioLaki)
                                .addGap(18, 18, 18)
                                .addComponent(radioPerempuan))
                            .addComponent(dateChooserLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jcbJabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioLaki)
                    .addComponent(radioPerempuan)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txProvinsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txProvinsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txProvinsiActionPerformed

    private void txKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txKotaActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.controller.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        this.controller.action();
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPegawaiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPegawaiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPegawaiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPegawaiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormPegawaiDialog dialog = new FormPegawaiDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dateChooserLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcbJabatan;
    private javax.swing.JRadioButton radioLaki;
    private javax.swing.JRadioButton radioPerempuan;
    private javax.swing.JTextArea txAreaAlamat;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txKota;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txPhone;
    private javax.swing.JTextField txProvinsi;
    private javax.swing.JTextField txTempatLahir;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the dimensi
     */
    public Dimension getDimensi() {
        return dimensi;
    }

    /**
     * @param dimensi the dimensi to set
     */
    public void setDimensi(Dimension dimensi) {
        this.dimensi = dimensi;
    }

    /**
     * @return the btnCancel
     */
    public javax.swing.JButton getBtnCancel() {
        return btnCancel;
    }

    /**
     * @param btnCancel the btnCancel to set
     */
    public void setBtnCancel(javax.swing.JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    /**
     * @return the btnSimpan
     */
    public javax.swing.JButton getBtnSimpan() {
        return btnSimpan;
    }

    /**
     * @param btnSimpan the btnSimpan to set
     */
    public void setBtnSimpan(javax.swing.JButton btnSimpan) {
        this.btnSimpan = btnSimpan;
    }

    /**
     * @return the dateChooserLahir
     */
    public com.toedter.calendar.JDateChooser getDateChooserLahir() {
        return dateChooserLahir;
    }

    /**
     * @param dateChooserLahir the dateChooserLahir to set
     */
    public void setDateChooserLahir(com.toedter.calendar.JDateChooser dateChooserLahir) {
        this.dateChooserLahir = dateChooserLahir;
    }

    /**
     * @return the radioLaki
     */
    public javax.swing.JRadioButton getRadioLaki() {
        return radioLaki;
    }

    /**
     * @param radioLaki the radioLaki to set
     */
    public void setRadioLaki(javax.swing.JRadioButton radioLaki) {
        this.radioLaki = radioLaki;
    }

    /**
     * @return the radioPerempuan
     */
    public javax.swing.JRadioButton getRadioPerempuan() {
        return radioPerempuan;
    }

    /**
     * @param radioPerempuan the radioPerempuan to set
     */
    public void setRadioPerempuan(javax.swing.JRadioButton radioPerempuan) {
        this.radioPerempuan = radioPerempuan;
    }

    /**
     * @return the txAreaAlamat
     */
    public javax.swing.JTextArea getTxAreaAlamat() {
        return txAreaAlamat;
    }

    /**
     * @param txAreaAlamat the txAreaAlamat to set
     */
    public void setTxAreaAlamat(javax.swing.JTextArea txAreaAlamat) {
        this.txAreaAlamat = txAreaAlamat;
    }

    /**
     * @return the txId
     */
    public javax.swing.JTextField getTxId() {
        return txId;
    }

    /**
     * @param txId the txId to set
     */
    public void setTxId(javax.swing.JTextField txId) {
        this.txId = txId;
    }

    /**
     * @return the txKota
     */
    public javax.swing.JTextField getTxKota() {
        return txKota;
    }

    /**
     * @param txKota the txKota to set
     */
    public void setTxKota(javax.swing.JTextField txKota) {
        this.txKota = txKota;
    }

    /**
     * @return the txNama
     */
    public javax.swing.JTextField getTxNama() {
        return txNama;
    }

    /**
     * @param txNama the txNama to set
     */
    public void setTxNama(javax.swing.JTextField txNama) {
        this.txNama = txNama;
    }

    /**
     * @return the txPhone
     */
    public javax.swing.JTextField getTxPhone() {
        return txPhone;
    }

    /**
     * @param txPhone the txPhone to set
     */
    public void setTxPhone(javax.swing.JTextField txPhone) {
        this.txPhone = txPhone;
    }

    /**
     * @return the txProvinsi
     */
    public javax.swing.JTextField getTxProvinsi() {
        return txProvinsi;
    }

    /**
     * @param txProvinsi the txProvinsi to set
     */
    public void setTxProvinsi(javax.swing.JTextField txProvinsi) {
        this.txProvinsi = txProvinsi;
    }

    /**
     * @return the txTempatLahir
     */
    public javax.swing.JTextField getTxTempatLahir() {
        return txTempatLahir;
    }

    /**
     * @param txTempatLahir the txTempatLahir to set
     */
    public void setTxTempatLahir(javax.swing.JTextField txTempatLahir) {
        this.txTempatLahir = txTempatLahir;
    }

    /**
     * @return the jcbJabatan
     */
    public javax.swing.JComboBox getJcbJabatan() {
        return jcbJabatan;
    }

    /**
     * @param jcbJabatan the jcbJabatan to set
     */
    public void setJcbJabatan(javax.swing.JComboBox jcbJabatan) {
        this.jcbJabatan = jcbJabatan;
    }

    /**
     * @return the action
     */
    public int getAction() {
        return action;
    }

    /**
     * @param action the action to set
     */
    public void setAction(int action) {
        this.action = action;
    }
}
