/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package analisasistem.view.registrasi;

import analisasistem.controller.RegistrasiDialogController;
import analisasistem.dao.ReservasiDAO;
import analisasistem.entity.Reservasi;
import analisasistem.interfaces.ReservasiInterface;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Raka New
 */
public class FormRegistrasi extends javax.swing.JDialog {

    /**
     * Creates new form FormRegistrasi
     */
    private int action = 1; // 1: insert 2: update
    private Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize();
    private RegistrasiDialogController controller;
    public FormRegistrasi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(dimensi.width/2-this.getWidth()/2, dimensi.height/2-this.getHeight()/2);
        this.controller = new RegistrasiDialogController(this);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txIdentitasNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jenisIdentitas = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        radioFemale = new javax.swing.JRadioButton();
        radioMale = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txTempat = new javax.swing.JTextField();
        jcbTanggalLahir = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txAlamat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txProvinsi = new javax.swing.JTextField();
        txNegara = new javax.swing.JTextField();
        txPhone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        arrivalNoTransfer = new javax.swing.JRadioButton();
        jcbCheckIn = new com.toedter.calendar.JDateChooser();
        jcbCheckOut = new com.toedter.calendar.JDateChooser();
        txPax = new javax.swing.JTextField();
        arrivalYesTransfer = new javax.swing.JRadioButton();
        departureYesTransfer = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        noReservasi = new javax.swing.JTextField();
        noRegistrasi = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txArrivalNo = new javax.swing.JTextField();
        txDepartureTime = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        departureNoTransfer = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txDateReg = new javax.swing.JTextField();
        txArrivalTime = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txDepartureNo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txAgent = new javax.swing.JTextField();
        txRooms = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnCekRsv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Guest Detail"));

        jLabel3.setText("No. Identitas");

        jLabel4.setText("Jenis Identitas");

        jenisIdentitas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KTP", "SIM", "Passport" }));

        jLabel5.setText("Nama");

        jLabel6.setText("Gender");

        radioFemale.setText("Female");

        radioMale.setText("Male");

        jLabel7.setText("Tempat Lahir");

        jLabel8.setText("Tanggal Lahir");

        jLabel9.setText("Alamat");

        txAlamat.setColumns(20);
        txAlamat.setRows(3);
        jScrollPane1.setViewportView(txAlamat);

        jLabel1.setText("Provinsi");

        jLabel2.setText("Negara");

        jLabel10.setText("Phone");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txPhone)
                    .addComponent(txNegara)
                    .addComponent(jcbTanggalLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radioFemale)
                        .addGap(36, 36, 36)
                        .addComponent(radioMale))
                    .addComponent(txIdentitasNo)
                    .addComponent(jenisIdentitas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txNama)
                    .addComponent(txTempat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(txProvinsi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txIdentitasNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jenisIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(radioFemale)
                    .addComponent(radioMale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNegara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Reservation Detail"));

        jLabel19.setText("Arrival Time");

        arrivalNoTransfer.setText("No");

        arrivalYesTransfer.setText("Yes");

        departureYesTransfer.setText("Yes");

        jLabel14.setText("Pax");

        noReservasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noReservasiKeyPressed(evt);
            }
        });

        noRegistrasi.setEditable(false);
        noRegistrasi.setEnabled(false);

        jLabel22.setText("Departure Transfer");

        jLabel18.setText("Departure No.");

        jLabel15.setText("Check In");

        jLabel11.setText("No. Reservasi");

        jLabel21.setText("Arrival Transfer");

        departureNoTransfer.setText("No");

        jLabel13.setText("Date Reg.");

        jLabel16.setText("Check Out");

        txDateReg.setEditable(false);
        txDateReg.setEnabled(false);
        txDateReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDateRegActionPerformed(evt);
            }
        });

        jLabel20.setText("Departure Time");

        jLabel12.setText("No. Registrasi");

        jLabel17.setText("Arrival No.");

        jLabel23.setText("Agent");

        jLabel24.setText("Rooms");

        btnBrowse.setText("...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCekRsv.setText("...");
        btnCekRsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekRsvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel22))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txArrivalNo)
                    .addComponent(jcbCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noRegistrasi)
                    .addComponent(txDateReg)
                    .addComponent(txPax)
                    .addComponent(txArrivalTime)
                    .addComponent(txDepartureNo)
                    .addComponent(txDepartureTime)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txRooms)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowse))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txAgent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arrivalYesTransfer)
                            .addComponent(departureYesTransfer))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(departureNoTransfer)
                            .addComponent(arrivalNoTransfer))
                        .addGap(0, 228, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(noReservasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCekRsv)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(noReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCekRsv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(noRegistrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txDateReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txPax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBrowse))
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txArrivalNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txDepartureNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(txDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(arrivalYesTransfer)
                    .addComponent(arrivalNoTransfer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(departureYesTransfer)
                    .addComponent(departureNoTransfer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOk)
                            .addComponent(btnCancel))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        this.getController().action();
    }//GEN-LAST:event_btnOkActionPerformed

    private void txDateRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDateRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDateRegActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.getController().close();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        this.getController().chooseRooms();
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.controller.chooseAgents();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCekRsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekRsvActionPerformed
        // TODO add your handling code here:
        this.controller.cekReservasi();
        
    }//GEN-LAST:event_btnCekRsvActionPerformed

    private void noReservasiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noReservasiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            this.controller.cekReservasi();
        }
    }//GEN-LAST:event_noReservasiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormRegistrasi dialog = new FormRegistrasi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton arrivalNoTransfer;
    private javax.swing.JRadioButton arrivalYesTransfer;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCekRsv;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton departureNoTransfer;
    private javax.swing.JRadioButton departureYesTransfer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jcbCheckIn;
    private com.toedter.calendar.JDateChooser jcbCheckOut;
    private com.toedter.calendar.JDateChooser jcbTanggalLahir;
    private javax.swing.JComboBox jenisIdentitas;
    private javax.swing.JTextField noRegistrasi;
    private javax.swing.JTextField noReservasi;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTextField txAgent;
    private javax.swing.JTextArea txAlamat;
    private javax.swing.JTextField txArrivalNo;
    private javax.swing.JTextField txArrivalTime;
    private javax.swing.JTextField txDateReg;
    private javax.swing.JTextField txDepartureNo;
    private javax.swing.JTextField txDepartureTime;
    private javax.swing.JTextField txIdentitasNo;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txNegara;
    private javax.swing.JTextField txPax;
    private javax.swing.JTextField txPhone;
    private javax.swing.JTextField txProvinsi;
    private javax.swing.JTextField txRooms;
    private javax.swing.JTextField txTempat;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the arrivalNoTransfer
     */
    public javax.swing.JRadioButton getArrivalNoTransfer() {
        return arrivalNoTransfer;
    }

    /**
     * @param arrivalNoTransfer the arrivalNoTransfer to set
     */
    public void setArrivalNoTransfer(javax.swing.JRadioButton arrivalNoTransfer) {
        this.arrivalNoTransfer = arrivalNoTransfer;
    }

    /**
     * @return the arrivalYesTransfer
     */
    public javax.swing.JRadioButton getArrivalYesTransfer() {
        return arrivalYesTransfer;
    }

    /**
     * @param arrivalYesTransfer the arrivalYesTransfer to set
     */
    public void setArrivalYesTransfer(javax.swing.JRadioButton arrivalYesTransfer) {
        this.arrivalYesTransfer = arrivalYesTransfer;
    }

    /**
     * @return the btnCancel
     */
    public javax.swing.JButton getBtnCancel() {
        return btnCancel;
    }

    /**
     * @param btnCancel the btnCancel to set
     */
    public void setBtnCancel(javax.swing.JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    /**
     * @return the btnOk
     */
    public javax.swing.JButton getBtnOk() {
        return btnOk;
    }

    /**
     * @param btnOk the btnOk to set
     */
    public void setBtnOk(javax.swing.JButton btnOk) {
        this.btnOk = btnOk;
    }

    /**
     * @return the departureNoTransfer
     */
    public javax.swing.JRadioButton getDepartureNoTransfer() {
        return departureNoTransfer;
    }

    /**
     * @param departureNoTransfer the departureNoTransfer to set
     */
    public void setDepartureNoTransfer(javax.swing.JRadioButton departureNoTransfer) {
        this.departureNoTransfer = departureNoTransfer;
    }

    /**
     * @return the departureYesTransfer
     */
    public javax.swing.JRadioButton getDepartureYesTransfer() {
        return departureYesTransfer;
    }

    /**
     * @param departureYesTransfer the departureYesTransfer to set
     */
    public void setDepartureYesTransfer(javax.swing.JRadioButton departureYesTransfer) {
        this.departureYesTransfer = departureYesTransfer;
    }

    /**
     * @return the jcbCheckIn
     */
    public com.toedter.calendar.JDateChooser getJcbCheckIn() {
        return jcbCheckIn;
    }

    /**
     * @param jcbCheckIn the jcbCheckIn to set
     */
    public void setJcbCheckIn(com.toedter.calendar.JDateChooser jcbCheckIn) {
        this.jcbCheckIn = jcbCheckIn;
    }

    /**
     * @return the jcbCheckOut
     */
    public com.toedter.calendar.JDateChooser getJcbCheckOut() {
        return jcbCheckOut;
    }

    /**
     * @param jcbCheckOut the jcbCheckOut to set
     */
    public void setJcbCheckOut(com.toedter.calendar.JDateChooser jcbCheckOut) {
        this.jcbCheckOut = jcbCheckOut;
    }

    /**
     * @return the jcbTanggalLahir
     */
    public com.toedter.calendar.JDateChooser getJcbTanggalLahir() {
        return jcbTanggalLahir;
    }

    /**
     * @param jcbTanggalLahir the jcbTanggalLahir to set
     */
    public void setJcbTanggalLahir(com.toedter.calendar.JDateChooser jcbTanggalLahir) {
        this.jcbTanggalLahir = jcbTanggalLahir;
    }

    /**
     * @return the jenisIdentitas
     */
    public javax.swing.JComboBox getJenisIdentitas() {
        return jenisIdentitas;
    }

    /**
     * @param jenisIdentitas the jenisIdentitas to set
     */
    public void setJenisIdentitas(javax.swing.JComboBox jenisIdentitas) {
        this.jenisIdentitas = jenisIdentitas;
    }

    /**
     * @return the noRegistrasi
     */
    public javax.swing.JTextField getNoRegistrasi() {
        return noRegistrasi;
    }

    /**
     * @param noRegistrasi the noRegistrasi to set
     */
    public void setNoRegistrasi(javax.swing.JTextField noRegistrasi) {
        this.noRegistrasi = noRegistrasi;
    }

    /**
     * @return the noReservasi
     */
    public javax.swing.JTextField getNoReservasi() {
        return noReservasi;
    }

    /**
     * @param noReservasi the noReservasi to set
     */
    public void setNoReservasi(javax.swing.JTextField noReservasi) {
        this.noReservasi = noReservasi;
    }

    /**
     * @return the radioFemale
     */
    public javax.swing.JRadioButton getRadioFemale() {
        return radioFemale;
    }

    /**
     * @param radioFemale the radioFemale to set
     */
    public void setRadioFemale(javax.swing.JRadioButton radioFemale) {
        this.radioFemale = radioFemale;
    }

    /**
     * @return the radioMale
     */
    public javax.swing.JRadioButton getRadioMale() {
        return radioMale;
    }

    /**
     * @param radioMale the radioMale to set
     */
    public void setRadioMale(javax.swing.JRadioButton radioMale) {
        this.radioMale = radioMale;
    }

    /**
     * @return the txAlamat
     */
    public javax.swing.JTextArea getTxAlamat() {
        return txAlamat;
    }

    /**
     * @param txAlamat the txAlamat to set
     */
    public void setTxAlamat(javax.swing.JTextArea txAlamat) {
        this.txAlamat = txAlamat;
    }

    /**
     * @return the txArrivalNo
     */
    public javax.swing.JTextField getTxArrivalNo() {
        return txArrivalNo;
    }

    /**
     * @param txArrivalNo the txArrivalNo to set
     */
    public void setTxArrivalNo(javax.swing.JTextField txArrivalNo) {
        this.txArrivalNo = txArrivalNo;
    }

    /**
     * @return the txArrivalTime
     */
    public javax.swing.JTextField getTxArrivalTime() {
        return txArrivalTime;
    }

    /**
     * @param txArrivalTime the txArrivalTime to set
     */
    public void setTxArrivalTime(javax.swing.JTextField txArrivalTime) {
        this.txArrivalTime = txArrivalTime;
    }

    /**
     * @return the txDateReg
     */
    public javax.swing.JTextField getTxDateReg() {
        return txDateReg;
    }

    /**
     * @param txDateReg the txDateReg to set
     */
    public void setTxDateReg(javax.swing.JTextField txDateReg) {
        this.txDateReg = txDateReg;
    }

    /**
     * @return the txDepartureNo
     */
    public javax.swing.JTextField getTxDepartureNo() {
        return txDepartureNo;
    }

    /**
     * @param txDepartureNo the txDepartureNo to set
     */
    public void setTxDepartureNo(javax.swing.JTextField txDepartureNo) {
        this.txDepartureNo = txDepartureNo;
    }

    /**
     * @return the txDepartureTime
     */
    public javax.swing.JTextField getTxDepartureTime() {
        return txDepartureTime;
    }

    /**
     * @param txDepartureTime the txDepartureTime to set
     */
    public void setTxDepartureTime(javax.swing.JTextField txDepartureTime) {
        this.txDepartureTime = txDepartureTime;
    }

    /**
     * @return the txIdentitasNo
     */
    public javax.swing.JTextField getTxIdentitasNo() {
        return txIdentitasNo;
    }

    /**
     * @param txIdentitasNo the txIdentitasNo to set
     */
    public void setTxIdentitasNo(javax.swing.JTextField txIdentitasNo) {
        this.txIdentitasNo = txIdentitasNo;
    }

    /**
     * @return the txNama
     */
    public javax.swing.JTextField getTxNama() {
        return txNama;
    }

    /**
     * @param txNama the txNama to set
     */
    public void setTxNama(javax.swing.JTextField txNama) {
        this.txNama = txNama;
    }

    /**
     * @return the txNegara
     */
    public javax.swing.JTextField getTxNegara() {
        return txNegara;
    }

    /**
     * @param txNegara the txNegara to set
     */
    public void setTxNegara(javax.swing.JTextField txNegara) {
        this.txNegara = txNegara;
    }

    /**
     * @return the txPax
     */
    public javax.swing.JTextField getTxPax() {
        return txPax;
    }

    /**
     * @param txPax the txPax to set
     */
    public void setTxPax(javax.swing.JTextField txPax) {
        this.txPax = txPax;
    }

    /**
     * @return the txPhone
     */
    public javax.swing.JTextField getTxPhone() {
        return txPhone;
    }

    /**
     * @param txPhone the txPhone to set
     */
    public void setTxPhone(javax.swing.JTextField txPhone) {
        this.txPhone = txPhone;
    }

    /**
     * @return the txProvinsi
     */
    public javax.swing.JTextField getTxProvinsi() {
        return txProvinsi;
    }

    /**
     * @param txProvinsi the txProvinsi to set
     */
    public void setTxProvinsi(javax.swing.JTextField txProvinsi) {
        this.txProvinsi = txProvinsi;
    }

    /**
     * @return the txTempat
     */
    public javax.swing.JTextField getTxTempat() {
        return txTempat;
    }

    /**
     * @param txTempat the txTempat to set
     */
    public void setTxTempat(javax.swing.JTextField txTempat) {
        this.txTempat = txTempat;
    }

    /**
     * @return the txAgent
     */
    public javax.swing.JTextField getTxAgent() {
        return txAgent;
    }

    /**
     * @param txAgent the txAgent to set
     */
    public void setTxAgent(javax.swing.JTextField txAgent) {
        this.txAgent = txAgent;
    }

    /**
     * @return the txRooms
     */
    public javax.swing.JTextField getTxRooms() {
        return txRooms;
    }

    /**
     * @param txRooms the txRooms to set
     */
    public void setTxRooms(javax.swing.JTextField txRooms) {
        this.txRooms = txRooms;
    }

    /**
     * @return the controller
     */
    public RegistrasiDialogController getController() {
        return controller;
    }

    /**
     * @param controller the controller to set
     */
    public void setController(RegistrasiDialogController controller) {
        this.controller = controller;
    }

    /**
     * @return the action
     */
    public int getAction() {
        return action;
    }

    /**
     * @param action the action to set
     */
    public void setAction(int action) {
        this.action = action;
    }
}
