/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package analisasistem.view;

/**
 *
 * @author RakaMSM
 */

public class AccordionPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccordionPanel
     */
    public AccordionPanel() {
        initComponents();
    }
    public void setParent(){
        
    }
    public void recreateLayout(){
        this.removeAll();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        this.setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }
    public void menuFalse(){
        mTaskButton4.setSelected(false);
        mTaskButton1.setSelected(false);
        mTaskButton2.setSelected(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        mTaskButton4 = new analisasistem.view.MTaskButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listMaster = new javax.swing.JList();
        mTaskButton1 = new analisasistem.view.MTaskButton();
        mTaskButton2 = new analisasistem.view.MTaskButton();
        mTaskButton3 = new analisasistem.view.MTaskButton();

        jScrollPane2.setAlignmentX(0.0F);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jScrollPane3.setAlignmentX(0.0F);

        jTree1.setRootVisible(false);
        jScrollPane3.setViewportView(jTree1);

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        mTaskButton4.setText("Master Data");
        mTaskButton4.setParentComp(this);
        mTaskButton4.setResizeComponent(true);
        mTaskButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTaskButton4ActionPerformed(evt);
            }
        });
        add(mTaskButton4);

        jScrollPane4.setAlignmentX(0.0F);

        listMaster.setBackground(new java.awt.Color(207, 207, 208));
        listMaster.setForeground(new java.awt.Color(51, 51, 51));
        listMaster.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Customer", "Jenis Akomodasi", "Car", "Pegawai" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMasterMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listMaster);

        add(jScrollPane4);

        mTaskButton1.setText("Transaksi");
        mTaskButton1.setParentComp(this);
        mTaskButton1.setResizeComponent(true);
        mTaskButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTaskButton1ActionPerformed(evt);
            }
        });
        add(mTaskButton1);

        mTaskButton2.setText("Report");
        mTaskButton2.setParentComp(this);
        mTaskButton2.setResizeComponent(true);
        mTaskButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTaskButton2ActionPerformed(evt);
            }
        });
        add(mTaskButton2);

        mTaskButton3.setText("Users");
        mTaskButton3.setParentComp(this);
        mTaskButton3.setResizeComponent(true);
        add(mTaskButton3);
    }// </editor-fold>//GEN-END:initComponents

    private void mTaskButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTaskButton4ActionPerformed
        // TODO add your handling code here:
        menuFalse();
        mTaskButton4.setSelected(true);
        this.recreateLayout();
        add(mTaskButton4);
        add(jScrollPane4);
        add(mTaskButton1);
        add(mTaskButton2);
        revalidate();
    }//GEN-LAST:event_mTaskButton4ActionPerformed

    private void mTaskButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTaskButton1ActionPerformed
        // TODO add your handling code here:
        menuFalse();
        mTaskButton1.setSelected(true);
        this.recreateLayout();
        add(mTaskButton4);
        
        add(mTaskButton1);
        add(jScrollPane2);
        add(mTaskButton2);
        revalidate();
    }//GEN-LAST:event_mTaskButton1ActionPerformed

    private void mTaskButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTaskButton2ActionPerformed
        // TODO add your handling code here:
        menuFalse();
        mTaskButton2.setSelected(true);
        this.recreateLayout();
        add(mTaskButton4);
        
        add(mTaskButton1);
        
        add(mTaskButton2);
        add(jScrollPane3);
        revalidate();
    }//GEN-LAST:event_mTaskButton2ActionPerformed

    private void listMasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMasterMouseClicked
        // TODO add your handling code here:
        System.out.println(this.listMaster.getSelectedIndex());
        System.out.println(this.listMaster.getSelectedValue());
    }//GEN-LAST:event_listMasterMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTree jTree1;
    private javax.swing.JList listMaster;
    private analisasistem.view.MTaskButton mTaskButton1;
    private analisasistem.view.MTaskButton mTaskButton2;
    private analisasistem.view.MTaskButton mTaskButton3;
    private analisasistem.view.MTaskButton mTaskButton4;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the listMaster
     */
    public javax.swing.JList getListMaster() {
        return listMaster;
    }

    /**
     * @param listMaster the listMaster to set
     */
    public void setListMaster(javax.swing.JList listMaster) {
        this.listMaster = listMaster;
    }
}
