
package analisasistem.view;

import analisasistem.controller.MainController;
import javax.swing.ImageIcon;

/**
 *
 * @author RakaMSM
 */
public class MainForm extends javax.swing.JFrame {
    /**
     * Deklarasi variable yang akan digunakan di class ini
     */
    private MainController mainController;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        doIcon();
        //this.setIconImage(new Image(getClass().getResource("")));
        this.mainController = new MainController(this);
        //this.panelSidebar.getListMaster().setSelectedIndex(2);
        this.mainController.setStartPage();
        
    }
    
    private void doIcon(){
        ImageIcon img = new javax.swing.ImageIcon(getClass().getResource("/analisasistem/image/biner.png"));
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnGuestInHouse = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNewRsv = new javax.swing.JMenuItem();
        menuAddRegistrasi = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuNewAgent = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        btnStartPage = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuTravelAgent = new javax.swing.JMenuItem();
        menuLaundryMaster = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuJabatan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAddReservation = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuReservasi = new javax.swing.JMenuItem();
        menuRegistrasi = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuTransaksiLaundry = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuLaundryTrans = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuLaporanReservasi = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jScrollPane2.setAlignmentX(0.0F);
        jScrollPane2.setAlignmentY(0.0F);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jScrollPane3.setAlignmentX(0.0F);
        jScrollPane3.setAlignmentY(0.0F);
        jScrollPane3.setViewportView(jTree1);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biner Hotel | Hotel Management System");
        setIconImage(getIconImage());

        MainPanel.setAlignmentX(0.0F);
        MainPanel.setAlignmentY(0.0F);
        MainPanel.setLayout(new java.awt.BorderLayout());
        MainPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setAlignmentX(0.0F);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisasistem/image/icon22/image.png"))); // NOI18N
        jButton1.setText("Deposit");
        jButton1.setToolTipText("Tambah Registrasi");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisasistem/image/icon22/image_add.png"))); // NOI18N
        jButton3.setText("Check out");
        jButton3.setToolTipText("Calendar Booking");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisasistem/image/icon22/image_add.png"))); // NOI18N
        jButton4.setText("Check in");
        jButton4.setToolTipText("Calendar Booking");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator7);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisasistem/image/icon22/user_male_add.png"))); // NOI18N
        jButton2.setText("Registrasi");
        jButton2.setToolTipText("Calendar Booking");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisasistem/image/icon22/users_male(1).png"))); // NOI18N
        jButton5.setText("Check in Group");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);
        jToolBar1.add(jSeparator8);

        btnGuestInHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisasistem/image/icon22/image.png"))); // NOI18N
        btnGuestInHouse.setText("Guest in House");
        btnGuestInHouse.setFocusable(false);
        btnGuestInHouse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuestInHouse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuestInHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuestInHouseActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuestInHouse);

        jMenu1.setText("File");

        menuNewRsv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNewRsv.setText("Add New Reservation...");
        menuNewRsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewRsvActionPerformed(evt);
            }
        });
        jMenu1.add(menuNewRsv);

        menuAddRegistrasi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menuAddRegistrasi.setText("Add New Registration...");
        menuAddRegistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddRegistrasiActionPerformed(evt);
            }
        });
        jMenu1.add(menuAddRegistrasi);

        jMenuItem19.setText("Add Payment Transaction ...");
        jMenu1.add(jMenuItem19);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon("D:\\Kampus\\SEMESTER VI\\ADSI\\Perangkat Lunak\\AnalisaSistem\\images\\blue\\addressbook22.png")); // NOI18N
        jMenuItem9.setText("Booking Calendar...");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);
        jMenu1.add(jSeparator2);

        menuNewAgent.setText("Add Travel Agents ...");
        menuNewAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewAgentActionPerformed(evt);
            }
        });
        jMenu1.add(menuNewAgent);

        jMenuItem18.setText("Add Acomodations Type");
        jMenu1.add(jMenuItem18);
        jMenu1.add(jSeparator6);

        btnStartPage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        btnStartPage.setText("Start page");
        btnStartPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartPageActionPerformed(evt);
            }
        });
        jMenu1.add(btnStartPage);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Exit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master Data");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuTravelAgent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuTravelAgent.setIcon(new javax.swing.ImageIcon("D:\\Kampus\\SEMESTER VI\\ADSI\\Perangkat Lunak\\AnalisaSistem\\images\\blue\\multi-agents.png")); // NOI18N
        menuTravelAgent.setText("Travel Agent...");
        menuTravelAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTravelAgentActionPerformed(evt);
            }
        });
        jMenu2.add(menuTravelAgent);

        menuLaundryMaster.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuLaundryMaster.setText("Price List Laundry...");
        menuLaundryMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaundryMasterActionPerformed(evt);
            }
        });
        jMenu2.add(menuLaundryMaster);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Jenis Kamar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Kamar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);
        jMenu2.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("D:\\Kampus\\SEMESTER VI\\ADSI\\Perangkat Lunak\\AnalisaSistem\\images\\blue\\male-user.png")); // NOI18N
        jMenuItem3.setText("Pegawai...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon("D:\\Kampus\\SEMESTER VI\\ADSI\\Perangkat Lunak\\AnalisaSistem\\images\\blue\\agent.png")); // NOI18N
        jMenuItem6.setText("Pengguna...");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        menuJabatan.setText("Jabatan");
        menuJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJabatanActionPerformed(evt);
            }
        });
        jMenu2.add(menuJabatan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        menuAddReservation.setText("Add New Reservation...");
        menuAddReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddReservationActionPerformed(evt);
            }
        });
        jMenu3.add(menuAddReservation);
        jMenu3.add(jSeparator3);

        menuReservasi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuReservasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analisasistem/image/icon22/folder.png"))); // NOI18N
        menuReservasi.setText("Transaksi Reservasi");
        menuReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReservasiActionPerformed(evt);
            }
        });
        jMenu3.add(menuReservasi);

        menuRegistrasi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuRegistrasi.setText("Transaksi Registrasi'");
        menuRegistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrasiActionPerformed(evt);
            }
        });
        jMenu3.add(menuRegistrasi);

        jMenuItem4.setText("Transaksi Check out");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Transaksi Pembayaran");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laundry");

        menuTransaksiLaundry.setText("Tambah Transaksi");
        menuTransaksiLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiLaundryActionPerformed(evt);
            }
        });
        jMenu4.add(menuTransaksiLaundry);
        jMenu4.add(jSeparator4);

        menuLaundryTrans.setText("Transaksi Laundry");
        menuLaundryTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaundryTransActionPerformed(evt);
            }
        });
        jMenu4.add(menuLaundryTrans);

        jMenuItem10.setText("Transaksi Pengambilan");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Bantuan");

        jMenuItem15.setIcon(new javax.swing.ImageIcon("D:\\Kampus\\SEMESTER VI\\ADSI\\Perangkat Lunak\\AnalisaSistem\\images\\blue\\rss22.png")); // NOI18N
        jMenuItem15.setText("Panduan Pemakaian");
        jMenu6.add(jMenuItem15);
        jMenu6.add(jSeparator5);

        jMenuItem16.setText("Tentang...");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Laporan");

        menuLaporanReservasi.setText("Laporan Reservasi");
        menuLaporanReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanReservasiActionPerformed(evt);
            }
        });
        jMenu7.add(menuLaporanReservasi);

        jMenuItem8.setText("Perfomance Invoice");
        jMenu7.add(jMenuItem8);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        analisasistem.view.roomtype.RoomTypeDialog roomTypeDialog = new analisasistem.view.roomtype.RoomTypeDialog(this,true);
        roomTypeDialog.setEnabled(true);
        roomTypeDialog.setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        analisasistem.view.roomtype.RoomTypeDialog roomTypeDialog = new analisasistem.view.roomtype.RoomTypeDialog(this,true);
        roomTypeDialog.setEnabled(true);
        roomTypeDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        analisasistem.view.rooms.RoomsDialog roomsDialog = new analisasistem.view.rooms.RoomsDialog(this,true);
        roomsDialog.setEnabled(true);
        roomsDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.mainController = new MainController(this);
        this.mainController.setPegawai();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuLaundryMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaundryMasterActionPerformed
        // TODO add your handling code here:
        this.mainController = new MainController(this);
        this.mainController.viewLaundryServiceMaster();
    }//GEN-LAST:event_menuLaundryMasterActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        this.mainController.exit();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void menuNewRsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewRsvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNewRsvActionPerformed

    private void menuReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReservasiActionPerformed
        // TODO add your handling code here:
        this.mainController.viewReservation();
    }//GEN-LAST:event_menuReservasiActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void menuNewAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewAgentActionPerformed
        // TODO add your handling code here:
        this.mainController.addAgent();
    }//GEN-LAST:event_menuNewAgentActionPerformed

    private void menuTravelAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTravelAgentActionPerformed
        // TODO add your handling code here:
        this.mainController.viewTravelAgent();
    }//GEN-LAST:event_menuTravelAgentActionPerformed

    private void menuJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJabatanActionPerformed
        // TODO add your handling code here:
        this.mainController.viewJabatanDialog();
    }//GEN-LAST:event_menuJabatanActionPerformed

    private void menuAddReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddReservationActionPerformed
        // TODO add your handling code here:
        this.mainController.addReservation();
    }//GEN-LAST:event_menuAddReservationActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        this.mainController.viewCalendarBooking();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.mainController.viewUsers();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuAddRegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddRegistrasiActionPerformed
        // TODO add your handling code here:
        this.mainController.addRegistration();
    }//GEN-LAST:event_menuAddRegistrasiActionPerformed

    private void menuRegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrasiActionPerformed
        // TODO add your handling code here:
        this.mainController.viewRegistrasi();
    }//GEN-LAST:event_menuRegistrasiActionPerformed

    private void menuTransaksiLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiLaundryActionPerformed
        // TODO add your handling code here:
        this.mainController.addTransaksiLaundry();
    }//GEN-LAST:event_menuTransaksiLaundryActionPerformed

    private void menuLaundryTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaundryTransActionPerformed
        // TODO add your handling code here:
        this.mainController.viewTransaksiLaundry();
    }//GEN-LAST:event_menuLaundryTransActionPerformed

    private void menuLaporanReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanReservasiActionPerformed
        // TODO add your handling code here:
        this.mainController.laporanReservasi();
    }//GEN-LAST:event_menuLaporanReservasiActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnStartPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartPageActionPerformed
        // TODO add your handling code here:
        this.mainController.setStartPage();
    }//GEN-LAST:event_btnStartPageActionPerformed

    private void btnGuestInHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuestInHouseActionPerformed
        // TODO add your handling code here:
        this.mainController.viewRegistrasi();
    }//GEN-LAST:event_btnGuestInHouseActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.mainController.addRegistration();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btnGuestInHouse;
    private javax.swing.JMenuItem btnStartPage;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuItem menuAddRegistrasi;
    private javax.swing.JMenuItem menuAddReservation;
    private javax.swing.JMenuItem menuJabatan;
    private javax.swing.JMenuItem menuLaporanReservasi;
    private javax.swing.JMenuItem menuLaundryMaster;
    private javax.swing.JMenuItem menuLaundryTrans;
    private javax.swing.JMenuItem menuNewAgent;
    private javax.swing.JMenuItem menuNewRsv;
    private javax.swing.JMenuItem menuRegistrasi;
    private javax.swing.JMenuItem menuReservasi;
    private javax.swing.JMenuItem menuTransaksiLaundry;
    private javax.swing.JMenuItem menuTravelAgent;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the MainPanel
     */
    public javax.swing.JPanel getMainPanel() {
        return MainPanel;
    }

    /**
     * @param MainPanel the MainPanel to set
     */
    public void setMainPanel(javax.swing.JPanel MainPanel) {
        this.MainPanel = MainPanel;
    }
    /**
     *
     */
    public void showPegawai(){
        this.mainController = new MainController(this);
        this.mainController.setPegawai();}
    
}
