/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package analisasistem.view.reservasi;

/**
 *
 * @author Raka New
 */
public class ReservasiPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form ReservasiPanel
     */
    
    /**
     * 
     */
    analisasistem.controller.ReservasiPanelController controller;
    public ReservasiPanel() {
        initComponents();
        this.controller =  new analisasistem.controller.ReservasiPanelController(this);
        this.staticConfig();
    }
    
    private void staticConfig(){
        this.controller.isiTable();
        analisasistem.library.TableStyle style = new analisasistem.library.TableStyle();
        style.setSize(this.getTbReservasi(), new int[]{10,80,150,100,100,100,100,100},true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbReservasi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnTambahBaru = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        tbReservasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbReservasi.setGridColor(new java.awt.Color(204, 204, 204));
        tbReservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbReservasiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbReservasi);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Kampus\\SEMESTER VI\\ADSI\\Perangkat Lunak\\AnalisaSistem\\images\\blue\\female-user.png")); // NOI18N
        jLabel1.setText("Data Reservasi");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnTambahBaru.setText("Tambah Baru");
        btnTambahBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBaruActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambahBaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnTambahBaru)
                    .addComponent(btnRefresh)
                    .addComponent(btnView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbReservasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReservasiMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            this.controller.viewData();
        }

    }//GEN-LAST:event_tbReservasiMouseClicked

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        this.controller.viewData();
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnTambahBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBaruActionPerformed
        // TODO add your handling code here:
        this.controller.addReservasi();
        
    }//GEN-LAST:event_btnTambahBaruActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambahBaru;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbReservasi;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnRefresh
     */
    public javax.swing.JButton getBtnRefresh() {
        return btnRefresh;
    }

    /**
     * @param btnRefresh the btnRefresh to set
     */
    public void setBtnRefresh(javax.swing.JButton btnRefresh) {
        this.btnRefresh = btnRefresh;
    }

    /**
     * @return the btnTambahBaru
     */
    public javax.swing.JButton getBtnTambahBaru() {
        return btnTambahBaru;
    }

    /**
     * @param btnTambahBaru the btnTambahBaru to set
     */
    public void setBtnTambahBaru(javax.swing.JButton btnTambahBaru) {
        this.btnTambahBaru = btnTambahBaru;
    }

    /**
     * @return the btnView
     */
    public javax.swing.JButton getBtnView() {
        return btnView;
    }

    /**
     * @param btnView the btnView to set
     */
    public void setBtnView(javax.swing.JButton btnView) {
        this.btnView = btnView;
    }

    /**
     * @return the jScrollPane2
     */
    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @param jScrollPane2 the jScrollPane2 to set
     */
    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    /**
     * @return the tbReservasi
     */
    public javax.swing.JTable getTbReservasi() {
        return tbReservasi;
    }

    /**
     * @param tbReservasi the tbReservasi to set
     */
    public void setTbReservasi(javax.swing.JTable tbReservasi) {
        this.tbReservasi = tbReservasi;
    }
}
