/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package analisasistem.view.reservasi;

import analisasistem.controller.ReservasiDialogController;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Raka New
 */
public class ReservasiFormDialog extends javax.swing.JDialog {

    /**
     * Creates new form ReservasiFormDialog
     */
    private int action;// 1: save, 2:update
    private ReservasiDialogController controller;
    private Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize();
    public ReservasiFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(dimensi.width/2-this.getWidth()/2, dimensi.height/2-this.getHeight()/2);
        this.controller = new ReservasiDialogController(this);
        this.staticConfig();
    }
 
    /**
     * 
     */
    private void staticConfig(){
        this.controller.defaultConfig();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txNoReservasi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txFirstName = new javax.swing.JTextField();
        txPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txCompany = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txArrivalTime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txDepartureTime = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txAreaMemo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txAddress = new javax.swing.JTextArea();
        txState = new javax.swing.JTextField();
        txNationallity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txRooms = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcbCheckIn = new com.toedter.calendar.JDateChooser();
        jcbCheckOut = new com.toedter.calendar.JDateChooser();
        txArrivalNo = new javax.swing.JTextField();
        txDepartureNo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        radioYesArrival = new javax.swing.JRadioButton();
        radioNoArrival = new javax.swing.JRadioButton();
        radioYesDeparture = new javax.swing.JRadioButton();
        radioNoDeparture = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txAgent = new javax.swing.JTextField();
        btnRoomsChooser = new javax.swing.JButton();
        btnBrowseAgent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Reservasi");

        jLabel1.setText("No. Reservasi");

        txNoReservasi.setEnabled(false);

        jLabel3.setText("Name");

        jLabel5.setText("Phone");

        jLabel6.setText("Company");

        jLabel9.setText("Arrival Time");

        txArrivalTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txArrivalTimeActionPerformed(evt);
            }
        });

        jLabel10.setText("Departure Time");

        btnCancel.setText("Close");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txAreaMemo.setColumns(20);
        txAreaMemo.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txAreaMemo.setRows(5);
        jScrollPane2.setViewportView(txAreaMemo);

        jLabel2.setText("Memo Message");

        txAddress.setColumns(20);
        txAddress.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txAddress.setRows(3);
        jScrollPane1.setViewportView(txAddress);

        jLabel7.setText("Email");

        jLabel8.setText("Address");

        jLabel11.setText("State");

        jLabel12.setText("Nationality");

        jLabel4.setText("Rooms");

        jLabel13.setText("Check In");

        jLabel14.setText("Check Out");

        jLabel15.setText("Arrival No.");

        jLabel16.setText("Departure No.");

        jLabel17.setText("Arrival Transfer");

        buttonGroup1.add(radioYesArrival);
        radioYesArrival.setText("Yes");

        buttonGroup1.add(radioNoArrival);
        radioNoArrival.setText("No");

        buttonGroup2.add(radioYesDeparture);
        radioYesDeparture.setText("Yes");

        buttonGroup2.add(radioNoDeparture);
        radioNoDeparture.setText("No");

        jLabel18.setText("Departure Transfer");

        jLabel19.setText("Agent");

        btnRoomsChooser.setText("...");
        btnRoomsChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomsChooserActionPerformed(evt);
            }
        });

        btnBrowseAgent.setText("...");
        btnBrowseAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txNationallity)
                                    .addComponent(txState)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(txEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txCompany, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txPhone, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(txNoReservasi))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txDepartureTime)
                            .addComponent(txArrivalTime)
                            .addComponent(jcbCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txDepartureNo)
                            .addComponent(txArrivalNo)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txRooms)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRoomsChooser))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioYesArrival)
                                            .addComponent(radioYesDeparture))
                                        .addGap(79, 79, 79)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(radioNoArrival)
                                            .addComponent(radioNoDeparture)))
                                    .addComponent(txAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBrowseAgent)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txNoReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnRoomsChooser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(jcbCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel14))
                    .addComponent(jcbCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txNationallity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txArrivalNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txDepartureNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(radioYesArrival)
                                    .addComponent(radioNoArrival))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioYesDeparture)
                                    .addComponent(radioNoDeparture)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBrowseAgent))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txArrivalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txArrivalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txArrivalTimeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.controller.close();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        this.controller.action();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRoomsChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomsChooserActionPerformed
        // TODO add your handling code here:
        this.controller.chooseRooms();
    }//GEN-LAST:event_btnRoomsChooserActionPerformed

    private void btnBrowseAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseAgentActionPerformed
        // TODO add your handling code here:
        this.controller.chooseAgents();
    }//GEN-LAST:event_btnBrowseAgentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservasiFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservasiFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservasiFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservasiFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReservasiFormDialog dialog = new ReservasiFormDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseAgent;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRoomsChooser;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jcbCheckIn;
    private com.toedter.calendar.JDateChooser jcbCheckOut;
    private javax.swing.JRadioButton radioNoArrival;
    private javax.swing.JRadioButton radioNoDeparture;
    private javax.swing.JRadioButton radioYesArrival;
    private javax.swing.JRadioButton radioYesDeparture;
    private javax.swing.JTextArea txAddress;
    private javax.swing.JTextField txAgent;
    private javax.swing.JTextArea txAreaMemo;
    private javax.swing.JTextField txArrivalNo;
    private javax.swing.JTextField txArrivalTime;
    private javax.swing.JTextField txCompany;
    private javax.swing.JTextField txDepartureNo;
    private javax.swing.JTextField txDepartureTime;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txFirstName;
    private javax.swing.JTextField txNationallity;
    private javax.swing.JTextField txNoReservasi;
    private javax.swing.JTextField txPhone;
    private javax.swing.JTextField txRooms;
    private javax.swing.JTextField txState;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnCancel
     */
    public javax.swing.JButton getBtnCancel() {
        return btnCancel;
    }

    /**
     * @param btnCancel the btnCancel to set
     */
    public void setBtnCancel(javax.swing.JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    /**
     * @return the btnSave
     */
    public javax.swing.JButton getBtnSave() {
        return btnSave;
    }

    /**
     * @param btnSave the btnSave to set
     */
    public void setBtnSave(javax.swing.JButton btnSave) {
        this.btnSave = btnSave;
    }

    /**
     * @return the jdcCheckIn
     */

    /**
     * @return the txArrivalTime
     */
    public javax.swing.JTextField getTxArrivalTime() {
        return txArrivalTime;
    }

    /**
     * @param txArrivalTime the txArrivalTime to set
     */
    public void setTxArrivalTime(javax.swing.JTextField txArrivalTime) {
        this.txArrivalTime = txArrivalTime;
    }

    /**
     * @return the txCompany
     */
    public javax.swing.JTextField getTxCompany() {
        return txCompany;
    }

    /**
     * @param txCompany the txCompany to set
     */
    public void setTxCompany(javax.swing.JTextField txCompany) {
        this.txCompany = txCompany;
    }

    /**
     * @return the txDepartureTime
     */
    public javax.swing.JTextField getTxDepartureTime() {
        return txDepartureTime;
    }

    /**
     * @param txDepartureTime the txDepartureTime to set
     */
    public void setTxDepartureTime(javax.swing.JTextField txDepartureTime) {
        this.txDepartureTime = txDepartureTime;
    }

    /**
     * @return the txFirstName
     */
    public javax.swing.JTextField getTxFirstName() {
        return txFirstName;
    }

    /**
     * @param txFirstName the txFirstName to set
     */
    public void setTxFirstName(javax.swing.JTextField txFirstName) {
        this.txFirstName = txFirstName;
    }

  


    /**
     * @return the txNoReservasi
     */
    public javax.swing.JTextField getTxNoReservasi() {
        return txNoReservasi;
    }

    /**
     * @param txNoReservasi the txNoReservasi to set
     */
    public void setTxNoReservasi(javax.swing.JTextField txNoReservasi) {
        this.txNoReservasi = txNoReservasi;
    }

    /**
     * @return the txPhone
     */
    public javax.swing.JTextField getTxPhone() {
        return txPhone;
    }

    /**
     * @param txPhone the txPhone to set
     */
    public void setTxPhone(javax.swing.JTextField txPhone) {
        this.txPhone = txPhone;
    }
    
    /**
     * 
     * @param action 
     */
    public void setAction(int action){
        this.action = action;
    }
    
    /**
     * 
     * @return 
     */
    public int getAction(){
        return action;
    }

    /**
     * @return the txAreaMemo
     */
    public javax.swing.JTextArea getTxAreaMemo() {
        return txAreaMemo;
    }

    /**
     * @param txAreaMemo the txAreaMemo to set
     */
    public void setTxAreaMemo(javax.swing.JTextArea txAreaMemo) {
        this.txAreaMemo = txAreaMemo;
    }

    /**
     * @return the jcbCheckOut
     */
    public com.toedter.calendar.JDateChooser getJcbCheckOut() {
        return jcbCheckOut;
    }

    /**
     * @param jcbCheckOut the jcbCheckOut to set
     */
    public void setJcbCheckOut(com.toedter.calendar.JDateChooser jcbCheckOut) {
        this.jcbCheckOut = jcbCheckOut;
    }

    /**
     * @return the radioNoArrival
     */
    public javax.swing.JRadioButton getRadioNoArrival() {
        return radioNoArrival;
    }

    /**
     * @param radioNoArrival the radioNoArrival to set
     */
    public void setRadioNoArrival(javax.swing.JRadioButton radioNoArrival) {
        this.radioNoArrival = radioNoArrival;
    }

    /**
     * @return the radioNoDeparture
     */
    public javax.swing.JRadioButton getRadioNoDeparture() {
        return radioNoDeparture;
    }

    /**
     * @param radioNoDeparture the radioNoDeparture to set
     */
    public void setRadioNoDeparture(javax.swing.JRadioButton radioNoDeparture) {
        this.radioNoDeparture = radioNoDeparture;
    }

    /**
     * @return the radioYesArrival
     */
    public javax.swing.JRadioButton getRadioYesArrival() {
        return radioYesArrival;
    }

    /**
     * @param radioYesArrival the radioYesArrival to set
     */
    public void setRadioYesArrival(javax.swing.JRadioButton radioYesArrival) {
        this.radioYesArrival = radioYesArrival;
    }

    /**
     * @return the txAddress
     */
    public javax.swing.JTextArea getTxAddress() {
        return txAddress;
    }

    /**
     * @param txAddress the txAddress to set
     */
    public void setTxAddress(javax.swing.JTextArea txAddress) {
        this.txAddress = txAddress;
    }

    /**
     * @return the txAgent
     */
    public javax.swing.JTextField getTxAgent() {
        return txAgent;
    }

    /**
     * @param txAgent the txAgent to set
     */
    public void setTxAgent(javax.swing.JTextField txAgent) {
        this.txAgent = txAgent;
    }

    /**
     * @return the txArrivalNo
     */
    public javax.swing.JTextField getTxArrivalNo() {
        return txArrivalNo;
    }

    /**
     * @param txArrivalNo the txArrivalNo to set
     */
    public void setTxArrivalNo(javax.swing.JTextField txArrivalNo) {
        this.txArrivalNo = txArrivalNo;
    }

    /**
     * @return the txDepartureNo
     */
    public javax.swing.JTextField getTxDepartureNo() {
        return txDepartureNo;
    }

    /**
     * @param txDepartureNo the txDepartureNo to set
     */
    public void setTxDepartureNo(javax.swing.JTextField txDepartureNo) {
        this.txDepartureNo = txDepartureNo;
    }

    /**
     * @return the txEmail
     */
    public javax.swing.JTextField getTxEmail() {
        return txEmail;
    }

    /**
     * @param txEmail the txEmail to set
     */
    public void setTxEmail(javax.swing.JTextField txEmail) {
        this.txEmail = txEmail;
    }

    /**
     * @return the txNationallity
     */
    public javax.swing.JTextField getTxNationallity() {
        return txNationallity;
    }

    /**
     * @param txNationallity the txNationallity to set
     */
    public void setTxNationallity(javax.swing.JTextField txNationallity) {
        this.txNationallity = txNationallity;
    }

    /**
     * @return the txRooms
     */
    public javax.swing.JTextField getTxRooms() {
        return txRooms;
    }

    /**
     * @param txRooms the txRooms to set
     */
    public void setTxRooms(javax.swing.JTextField txRooms) {
        this.txRooms = txRooms;
    }

    /**
     * @return the txState
     */
    public javax.swing.JTextField getTxState() {
        return txState;
    }

    /**
     * @param txState the txState to set
     */
    public void setTxState(javax.swing.JTextField txState) {
        this.txState = txState;
    }

    /**
     * @return the jcbCheckIn
     */
    public com.toedter.calendar.JDateChooser getJcbCheckIn() {
        return jcbCheckIn;
    }

    /**
     * @param jcbCheckIn the jcbCheckIn to set
     */
    public void setJcbCheckIn(com.toedter.calendar.JDateChooser jcbCheckIn) {
        this.jcbCheckIn = jcbCheckIn;
    }

    /**
     * @return the radioYesDeparture
     */
    public javax.swing.JRadioButton getRadioYesDeparture() {
        return radioYesDeparture;
    }

    /**
     * @param radioYesDeparture the radioYesDeparture to set
     */
    public void setRadioYesDeparture(javax.swing.JRadioButton radioYesDeparture) {
        this.radioYesDeparture = radioYesDeparture;
    }
}
