/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package analisasistem.view.users;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Raka New
 */
public class UserDialogForm extends javax.swing.JDialog {

    /**
     * Creates new form UserDialogForm
     */
    private analisasistem.controller.users.UserDialogFormController controller;
    private Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize();
    public UserDialogForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(dimensi.width/2- getWidth()/2, dimensi.height/2-getHeight());
        this.controller = new analisasistem.controller.users.UserDialogFormController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txPassword = new javax.swing.JTextField();
        btnAddPegawai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTambahPengguna = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txIdPengguna = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txNamaPengguna = new javax.swing.JTextField();
        txIdPegawai = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulir Pengguna");

        btnAddPegawai.setText("...");
        btnAddPegawai.setPreferredSize(new java.awt.Dimension(23, 20));
        btnAddPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPegawaiActionPerformed(evt);
            }
        });

        jLabel1.setText("Id Pengguna");

        btnTambahPengguna.setText("Tambah pengguna");
        btnTambahPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPenggunaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Pengguna");

        txIdPengguna.setEditable(false);

        jLabel3.setText("Password");

        jLabel4.setText("Pegawai");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTambahPengguna)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txIdPegawai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txIdPengguna)
                            .addComponent(txNamaPengguna)
                            .addComponent(txPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txIdPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNamaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambahPengguna)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPenggunaActionPerformed
        // TODO add your handling code here:
        this.controller.insert();
    }//GEN-LAST:event_btnTambahPenggunaActionPerformed

    private void btnAddPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPegawaiActionPerformed
        // TODO add your handling code here:
        this.controller.cariPegawai();
    }//GEN-LAST:event_btnAddPegawaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                UserDialogForm dialog = new UserDialogForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPegawai;
    private javax.swing.JButton btnTambahPengguna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txIdPegawai;
    private javax.swing.JTextField txIdPengguna;
    private javax.swing.JTextField txNamaPengguna;
    private javax.swing.JTextField txPassword;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnAddPegawai
     */
    public javax.swing.JButton getBtnAddPegawai() {
        return btnAddPegawai;
    }

    /**
     * @param btnAddPegawai the btnAddPegawai to set
     */
    public void setBtnAddPegawai(javax.swing.JButton btnAddPegawai) {
        this.btnAddPegawai = btnAddPegawai;
    }

    /**
     * @return the btnTambahPengguna
     */
    public javax.swing.JButton getBtnTambahPengguna() {
        return btnTambahPengguna;
    }

    /**
     * @param btnTambahPengguna the btnTambahPengguna to set
     */
    public void setBtnTambahPengguna(javax.swing.JButton btnTambahPengguna) {
        this.btnTambahPengguna = btnTambahPengguna;
    }

    /**
     * @return the txIdPegawai
     */
    public javax.swing.JTextField getTxIdPegawai() {
        return txIdPegawai;
    }

    /**
     * @param txIdPegawai the txIdPegawai to set
     */
    public void setTxIdPegawai(javax.swing.JTextField txIdPegawai) {
        this.txIdPegawai = txIdPegawai;
    }

    /**
     * @return the txIdPengguna
     */
    public javax.swing.JTextField getTxIdPengguna() {
        return txIdPengguna;
    }

    /**
     * @param txIdPengguna the txIdPengguna to set
     */
    public void setTxIdPengguna(javax.swing.JTextField txIdPengguna) {
        this.txIdPengguna = txIdPengguna;
    }

    /**
     * @return the txNamaPengguna
     */
    public javax.swing.JTextField getTxNamaPengguna() {
        return txNamaPengguna;
    }

    /**
     * @param txNamaPengguna the txNamaPengguna to set
     */
    public void setTxNamaPengguna(javax.swing.JTextField txNamaPengguna) {
        this.txNamaPengguna = txNamaPengguna;
    }

    /**
     * @return the txPassword
     */
    public javax.swing.JTextField getTxPassword() {
        return txPassword;
    }

    /**
     * @param txPassword the txPassword to set
     */
    public void setTxPassword(javax.swing.JTextField txPassword) {
        this.txPassword = txPassword;
    }
}
